/**
 * This file is auto-generated by the magic-imports Mitosis plugin.
 * Do not edit this file directly - any changes will be overwritten.
 * See mitosis.config.cjs for configuration.
 */

declare module "virtual:lucide" {
    export * from "lucide-react";
}

declare module "virtual:flow" {
    export { SolidFlow as Flow } from "@dschz/solid-flow";
    export { useSolidFlow as useFlow } from "@dschz/solid-flow";
    export { SolidFlowProvider as FlowProvider } from "@dschz/solid-flow";
    export * from "@dschz/solid-flow";
}
